"""Generate synthetic input data using Hamilton DAG."""

from os import PathLike
from pathlib import Path
from typing import Any

import numpy as np
import xarray as xr
from hamilton import driver
from hamilton.settings import ENABLE_POWER_USER_MODE

from ...config import (
    NodeSpec,
    ParsedConfig,
    ResampleSpec,
    expand_node_entries,
    resample_to_node_entry,
)
from ...dag.node import make_node_module
from ...io import dataset_to_dataframe, save_timeseries, unstack_if_gridded
from . import coords
from .fallback import build_fallback_module

_FLAT_SUFFIXES = {".csv", ".parquet", ".pq"}


def _set_random_seed(seed: int) -> None:
    np.random.seed(seed)


def _save_dataset_with_crs(ds: xr.Dataset, path: str | PathLike) -> None:
    """Save dataset to NetCDF, Zarr, CSV, Parquet, or JSON.

    CSV and Parquet are written as flat time-indexed tables (CRS not stored).
    JSON is written as a {variable: value} dict for static single-pixel data.
    NetCDF and Zarr receive a crs='EPSG:4326' global attribute.
    """
    import json

    p = Path(path)
    suffix = p.suffix.lower()

    if suffix == ".json":
        data = {str(var): float(ds[var].values.flat[0]) for var in ds.data_vars}
        with open(p, "w") as f:
            json.dump(data, f, indent=2)
        return

    if suffix in _FLAT_SUFFIXES:
        save_timeseries(dataset_to_dataframe(ds), path)
        return

    ds.attrs["crs"] = "EPSG:4326"

    if suffix in (".nc", ".netcdf"):
        ds.to_netcdf(path, engine="netcdf4")
    elif suffix == ".zarr" or (not suffix and p.is_dir()):
        ds.to_zarr(path)
    else:
        raise ValueError(
            f"Unsupported file extension: '{suffix}'. "
            "Use '.nc', '.netcdf', '.zarr', '.csv', '.parquet', or '.json'."
        )


def generate_synthetic_data(
    config: ParsedConfig,
    grid: tuple[int, int],
    n_days: int,
    seed: int = 42,
) -> None:
    """Generate synthetic input data using Hamilton DAG.

    Parameters
    ----------
    config : ParsedConfig
        Parsed configuration from load_config(). Input paths in config.input_specs
        are used as the destinations for the generated files.
    grid : tuple[int, int]
        Grid dimensions as (n_lat, n_lon).
    n_days : int
        Number of days to generate.
    seed : int
        Random seed for reproducibility.
    """
    _set_random_seed(seed)

    n_lat, n_lon = grid

    daily_spec = config.input_specs.get("daily")
    weekly_spec = config.input_specs.get("weekly")
    monthly_spec = config.input_specs.get("monthly")
    static_spec = config.input_specs.get("static")

    daily_vars: set[str] = set(daily_spec.vars) if daily_spec else set()
    weekly_vars: set[str] = set(weekly_spec.vars) if weekly_spec else set()
    monthly_vars: set[str] = set(monthly_spec.vars) if monthly_spec else set()
    static_vars: list[str] = list(static_spec.vars) if static_spec else []

    resample_specs: list[ResampleSpec] = []

    if weekly_vars:
        resample_specs.append(
            ResampleSpec(
                vars=sorted(weekly_vars), source_freq="daily", target_freq="weekly"
            )
        )
    daily_to_monthly_vars = daily_vars | weekly_vars | monthly_vars
    if daily_to_monthly_vars:
        resample_specs.append(
            ResampleSpec(
                vars=sorted(daily_to_monthly_vars),
                source_freq="daily",
                target_freq="monthly",
            )
        )

    driver_config: dict[str, Any] = {
        ENABLE_POWER_USER_MODE: True,
        "n_lat": n_lat,
        "n_lon": n_lon,
        "n_days": n_days,
        "start_date": "2020-01-01",
        "seed": seed,
    }

    # Resampling is the same fan-out passthrough-node mechanism the [[resample]]
    # preset uses: desugar each spec to node entries, expand, and generate a module.
    resample_entries = [resample_to_node_entry(s) for s in resample_specs]
    resample_node_specs = [
        NodeSpec.from_config(e) for e in expand_node_entries(resample_entries)
    ]
    resample_module = make_node_module(resample_node_specs)

    # Every requested variable is generated by the name-heuristic fallback module;
    # `coords` supplies the grid/time coordinate nodes they depend on.
    all_temporal_vars = sorted(daily_vars | weekly_vars | monthly_vars)
    modules = [
        coords,
        resample_module,
        build_fallback_module(all_temporal_vars, static_vars),
    ]

    dr = (
        driver.Builder()
        .with_modules(*modules)
        .with_config(driver_config)
        .allow_module_overrides()
        .build()
    )

    # Collect targets for each frequency
    daily_targets = [f"{v}_daily" for v in daily_vars]
    weekly_targets = [f"{v}_weekly" for v in sorted(weekly_vars)]
    monthly_targets = [
        f"{v}_monthly" for v in sorted(daily_to_monthly_vars | monthly_vars)
    ]

    all_targets = daily_targets + weekly_targets + monthly_targets + static_vars
    results = dr.execute(all_targets)  # type: ignore[reportArgumentType]

    if daily_vars and daily_spec:
        daily_ds = unstack_if_gridded(xr.merge([results[t] for t in daily_targets]))  # type: ignore[reportArgumentType]
        _save_dataset_with_crs(daily_ds, daily_spec.path)

    if weekly_vars and weekly_spec:
        weekly_ds = unstack_if_gridded(xr.merge([results[t] for t in weekly_targets]))  # type: ignore[reportArgumentType]
        _save_dataset_with_crs(weekly_ds, weekly_spec.path)

    if (daily_to_monthly_vars | monthly_vars) and monthly_spec:
        monthly_ds = unstack_if_gridded(xr.merge([results[t] for t in monthly_targets]))  # type: ignore[reportArgumentType]
        _save_dataset_with_crs(monthly_ds, monthly_spec.path)

    if static_spec:
        static_ds = unstack_if_gridded(xr.merge([results[v] for v in static_vars]))  # type: ignore[reportArgumentType]
        _save_dataset_with_crs(static_ds, static_spec.path)
